/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create__sign_in (void);
GtkWidget* create_log_in (void);
GtkWidget* create_admin (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_choix_fenetre (void);
GtkWidget* create_liste_des_alarmes (void);
GtkWidget* create_redirect (void);
GtkWidget* create_window_agentfoyer_loula (void);
GtkWidget* create_authentification (void);
GtkWidget* create_windowinscription (void);
GtkWidget* create_espaceagentfoyer (void);
GtkWidget* create_ajoutetudiant (void);
GtkWidget* create_window_modification (void);
GtkWidget* create_window_ahmed_loula (void);
GtkWidget* create_affichage_produit (void);
GtkWidget* create_ajout_produit (void);
GtkWidget* create_modifier_produit (void);
GtkWidget* create_ajout_capteur (void);
GtkWidget* create_affichage_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_capteur_defectueux (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_EMTinscription (void);
GtkWidget* create_espace_reclamation (void);
GtkWidget* create_serviceleplusrecla (void);
GtkWidget* create_EMTauthen (void);
