/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *redirect;
  GtkWidget *choix_fenetre;
  GtkWidget *sign_in;
  GtkWidget *log_in;
  GtkWidget *admin;
  GtkWidget *fenetre_ajout;
  GtkWidget *fenetre_afficher;
  GtkWidget *fenetre_modifier;
  GtkWidget *fenetre_supprimer;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */


  redirect=create_redirect ();
  gtk_widget_show (redirect);


  choix_fenetre = create_choix_fenetre ();
  


  sign_in = create__sign_in ();
  

  log_in = create_log_in ();
  

  admin = create_admin ();
  

  fenetre_ajout = create_fenetre_ajout ();
  

  fenetre_afficher = create_fenetre_afficher();
  

  fenetre_modifier = create_fenetre_modifier ();
  

  fenetre_supprimer = create_fenetre_supprimer ();
  


  gtk_main ();
  return 0;
}

